### ISSUE TITLE
Ability to add a dynamic IP address/hostname to Whitelist

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/bruteforcesettings#283] opened 2021-05-03 10:45 UTC
At the moment the Whitelist only accept IP to add.

One bureau only can get a dynamic IP. So all devices / server uses an dynamic IP address this place.

an option to resolve DNS to IP and renew every X (setable time) would be perfect.

**Comment by joshtrichards** [comment] 2024-01-07 18:20
Duplicate of #11

**Closed by joshtrichards** 2024-01-07 18:20 UTC
